language: python 
python: 
  - "3.4"
  - "3.5"
  - "3.6"
services: 
  - mysql
env: 
  -DJANGO=2.1.7 
install: 
  - pip3 install -r requirements.txt
script: 
  - python manage.py makemigrations dataincubator
  - python manage.py migrate
  - python manage.py test
